

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    expose:
      - 8000
    ports:
      - 8000:8000
    init: true

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    links:
        - server
    init: true

